version: "3.9"

services:
  postgres:
    container_name: delievery-service-postgres
    image: postgres:14.8-alpine3.18
    env_file:
      - ".env"
    environment:
      POSTGRES_DB: "${PG_DATABASE}"
      POSTGRES_USER: "${PG_USER}"
      POSTGRES_PASSWORD: "${PG_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    restart: unless-stopped
    network_mode: "host"

    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${PG_PORT}:${PG_PORT}"

volumes:
  postgres-data:
